name: Deploy

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'book/**'
      - '{{ cookiecutter.repo_directory }}/**'
      - 'scripts/**'
      - '.github/workflows/deploy.yaml'
      - 'cookiecutter.yaml'

    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure NASA Earthdata Login
      continue-on-error: true
      env:
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      run: |
        echo "machine urs.earthdata.nasa.gov login $EARTHDATA_USERNAME password $EARTHDATA_PASSWORD" > ~/.netrc
        chmod 0600 ~/.netrc

    - uses: ./.github/actions/buildresources
      # Expose login as ENV vars for alternative earthaccess login
      env:
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME}}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      with:
        jb-cache: false
        publish-to-gh: true
        jb-save: true
        token:  ${{ secrets.GITHUB_TOKEN }}
